[package]
name = "wasm-lib-example"
version = "1.3.0"
authors = ["tmtmt2209 <tmtmt2209@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "=0.2.25"
octavo-mac = "0.1.1"
octavo-digest = "0.1.2"
